version: 0.2

phases:
  install:
    commands:
      - echo Installing RSpec...
      - gem install rspec
  pre_build:
      - echo Preparing build...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
      - rspec HelloWorld_spec.rb 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.rb
