version: 0.2

phases:
  install:
    commands:
      - apt-get update -qq && apt-get install -y -qq nodejs # as Rails用JavaScript実行環境
      - gem install bundler --no-ri --no-doc
      - bundle install -j $(nproc) --path vendor
      - gem install rspec
  pre_build:
    commands:
      - bundle exec rails db:migrate
  build:
    commands:
      - rspec spec
artifacts:
  base-directory: coverage
